<?php

namespace App\Model;

use App\Observers\ZanObserver;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Zan extends Model
{
    protected $fillable = [ 'user_id' ];
    
    //关联用户表(一对多反向)
    public function user(){
        return $this->belongsTo (User::class);
    }
    
    public static function boot ()
    {
        self::observe (ZanObserver::class);
        parent::boot (); // TODO: Change the autogenerated stub
    }
    
    public function belongModel ()
    {
        return $this->morphTo ( 'zan' );
    }
}
